name: '${name}'
version: '${version}'
main: org.crashwho.crashCoinFlip.CrashCoinFlip
api-version: '1.21'
authors: [ CrashWho ]
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    ProtocolLib:
      load: BEFORE
      required: true
